corrosion_recognition_node:
  ros__parameters:
    subscribers:
      image_rgb: 'image_raw'
    publishers:
      debug_image: 'debug_image'
      recognition_topic: 'corrosion_recognition'
    network: 
      model: 'yolov8' #yolov8 OR unet2 OR deeplab
      weight_path: 'yolov8n.pt' #with the weight name also ex: ../weights/****.pt